### ISSUE TITLE
Expand accessibility walkthrough to get Stata running?

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/stata-fundamentals#11]
I believe students need to download a [Citrix Workspace App](https://www.citrix.com/downloads/workspace-app/) to access a remote copy of Stata. Getting a working directory path was a little frustrating for me, but this [UCB Library Guide](https://guides.lib.berkeley.edu/citrix) was helpful when I ran the workshop on my own.

**Comment by rstarowicz** [comment]
I added a link to instructions for using Citrix alongside the instructions linked for Stata.
