### ISSUE TITLE
File Updates to Clean Up Solutions File(s) and Google Slides

### ISSUE THREAD

**Issue by rstarowicz** [dlab-berkeley/stata-fundamentals#15]
The folders need version that is updated clearly with solution files.  Slides pulled from individual sessions into a shared Google Slide deck that can be modified regularly.

**Comment by rstarowicz** [comment]
I went through all of the Do Files last week and cleaned up all of the materials. I have just uploaded them to a folder in the Public Data > Workshop Materials > Stata Fundamentals > I, II & III Folder.  I marked the older versions for archive - is there a best place I should move them to?

**Comment by rstarowicz** [comment]
@pssachdeva Hi Pratik, I just realized that I probably should have tagged you in my last comment in this thread. I updated all of the do files including the solution files a few weeks ago and saved them into the folder Public Data > Workshop Materials > Stata Fundamentals > I, II & III Folder. I marked the older versions for archive.  Can you help me to move the updated do files into this Github? Do you know where I should save archived versions if we are doing that?

**Comment by pssachdeva** [comment]
Happy to move the new files into this repo. It's not necessary to save the old versions since git will automatically track all past versions of the workshop.
